### ISSUE TITLE
Nonexistent discount retrieved

### ISSUE THREAD

**Issue by aegroto** [sergioteula/python-amazon-paapi#42]
Hello!

A lot of times when I use the min_discount parameter on the "search_products" method I experience two issues:
- The items retrieved have a lower discount. This can be solved by filtering items manually later
- The discount in the "product.prices.price.savings.percentage" field is not present in Amazon. When I visit the product's page, there's no discount or there's a much lower one.

I've tried to access only the IT marketplace.

Here's a test case code snippet:

```
    min_discount = 70

    products = client.search_products(keywords="pc,usb", min_discount=min_discount, item_count=10)

    for product in products:
        discount = product.prices.price.savings.percentage

        if not discount or discount < min_discount:
            continue

        print("[{}%] {} {}".format(discount, product.title, product.url))
        print(product.info.product_group)
        print("---")
```

**Comment by sergioteula** [comment]
Sometimes Amazon API returns incorrect information, but that's something this wrapper can't change since it only helps managing the information provided by Amazon. I hope Amazon will improve someday it's API results, but for now the only way of getting more reliable information is with web scraping.
